linters-settings:
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: confluent-test
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - commentedOutCode

linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gofmt
    - goimports
    - revive
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
  disable:
    - gochecknoglobals
    - gocognit

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - dupl
    - path: test_build\.go
      linters:
        - gosec
        - errcheck
    # Allow main functions to have multiple exit points
    - path: main\.go
      linters:
        - gocritic
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - examples

run:
  timeout: 5m
  modules-download-mode: readonly